[tool.poetry]
name = "owphandfim"
version = "0.1.0"
description = "US operational FIM"
authors = ["Supath Dhital"]
license = "GPv3"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
pytest = "^8.3.3"
teehr = {git = "https://github.com/RTIInternational/teehr.git", rev = "main"}
numpy = "1.26.0"
pyarrow = "^14.0.1"
utils = "^1.0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
